export default {
	getReceMetaData: '/finance/receivables/verification/searchItem',
	getSalerData: '/finance/invoice/application/createUserList',
	getProjectData: '/finance/commonApi/getProjectByName',
	getBrandData: '/finance/commonApi/getBrandByName',
	getCompanyInfo: '/finance/commonApi/getCompanyCommonData',
	getAccountInfo: '/finance/commonApi/getAccountByName',
	getGiftAmount: '/finance/account/detail',
	getWarehouseAmount: '/finance/warehouse/getWarehouseList',
	getReceivableOffList: '/finance/receivables/verification/list',
	getReceOffDetailList: '/finance/receivables/verification/orderDetailList',
	getReceAddOffList: '/finance/receivables/order/orderListForVerification',
	addReceOffItem: '/finance/receivables/verification/commit',
	getOffItemInfo: '/finance/receivables/verification/detail',
	editReceOffItem: '/finance/receivables/verification/edit',
	getRequirementWithoutId: '/finance/commonApi/getRequirementInfoByName', 
	getRegionTeamName: '/finance/commonApi/getRegionTeamName',
	getBusinessType: '/finance/commonApi/getBusinessType',
	getCampaignDataByName: '/finance/commonApi/getCampaignDataByName',
	getReceivableListExportInfo: '/finance/receivables/verification/exportList',
	getReceivableDetailExportInfo: '/finance/receivables/verification/exportOrderList',
	getReceivableAddListExportInfo: '/finance/receivables/order/exportForVerification',
}
